name: Testing
on: [push, pull_request]

jobs:
  api-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo to the node
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          cd api
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest